- name: Adding host into playbook
  hosts: localhost
  become: yes

  tasks:
    - name: Add host as deploy
      add_host:
        hostname: "{{ (lookup('file', '../address.json') | from_json).get('deploy_ip') }}"
        groups: deploy

- name: Provisioning server's deploy
  hosts: deploy
  become: yes

  tasks:
    - name: Pull a simple-springboot-project image
      docker_image:
        name: a1kazakov/simple-springboot-project-image:0.0.1
        source: pull

    - name: Start a container with a simple-springboot-project image
      docker_container:
        name: simple-springboot-project
        image: a1kazakov/simple-springboot-project-image:0.0.1
        working_dir: /app
        command: ["java", "-jar", "target/app-0.0.1-SNAPSHOT.jar"]
        ports:
          - "8080:8080"